root: true
parser: "@typescript-eslint/parser"
plugins:
  - "@typescript-eslint"
extends:
  - "eslint:recommended"
  - "plugin:@typescript-eslint/recommended"
rules:
  no-magic-numbers:
    - warn
    - ignoreArrayIndexes: true
      ignoreDefaultValues: true
      ignore:
      - 0
      - 1
      - 2
  arrow-body-style:
    - warn
  semi:
    - warn
  sort-imports:
    - warn
  prefer-template:
    - warn
  comma-dangle:
    - warn
    - only-multiline
  camelcase:
    - warn
  max-classes-per-file:
    - warn
    - { max: 2 }
  complexity:
    - warn
    - { max: 10 }
  max-lines:
    - warn
    - { max: 500 }
  no-unused-vars:
    - off
  "@typescript-eslint/no-unused-vars":
    - warn
  no-cond-assign:
    - error
  no-template-curly-in-string:
    - error
  no-var:
    - error
  no-duplicate-imports:
    - error
  prefer-const:
    - error
  dot-notation:
    - error
  eol-last:
    - error
  "@typescript-eslint/array-type":
    - error
  "@typescript-eslint/explicit-function-return-type":
    - error
  "@typescript-eslint/explicit-member-accessibility":
    - error
    - accessibility: 'explicit'
      overrides:
        constructors: 'off'
  "@typescript-eslint/member-delimiter-style":
    - error
    - multiline:
        delimiter: 'semi'
        requireLast: true
      singleline:
        delimiter: 'semi'
        requireLast: false
  "@typescript-eslint/no-inferrable-types":
    - error
  "@typescript-eslint/no-explicit-any":
    - off
